name: optimus
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - aiohttp=3.11.11=pyhe1237c8_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - annotated-types=0.6.0=py312h06a4308_0
  - arrow-cpp=17.0.0=h865e1df_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hff2c3d7_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h2666983_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=hf5f93bc_1
  - aws-checksums=0.1.13=hf5f93bc_5
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.11.12=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=2.14.4=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distro=1.9.0=py312h06a4308_0
  - et_xmlfile=1.1.0=py312h06a4308_1
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py312h5eee18b_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.1.1=py312h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - jiter=0.6.1=py312hb02cf49_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.1=h6a678d5_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - multidict=6.1.0=pyh62beb40_2
  - multiprocess=0.70.15=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py312h5eee18b_1
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - propcache=0.2.0=py312h5eee18b_0
  - psutil=5.9.0=py312h5eee18b_1
  - psycopg2=2.9.9=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-xgboost=2.1.1=py312h06a4308_0
  - pyarrow=17.0.0=py312h526ad5a_0
  - pybind11-abi=5=hd3eb1b0_0
  - pymysql=1.1.1=py312h06a4308_0
  - pyparsing=3.1.2=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.7=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python-xxhash=2.0.2=py312h5eee18b_1
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_1
  - pyyaml=6.0.2=py312h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - regex=2024.9.11=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - s2n=1.3.27=h1b5e8cb_0
  - safetensors=0.4.5=py312hc50d6dc_1
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.13.1=py312hc5e2394_0
  - seaborn=0.13.2=py312h06a4308_3
  - sentence-transformers=3.3.1=pyhd8ed1ab_1
  - setuptools=75.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.0=py312h06a4308_0
  - sqlalchemy=2.0.41=py312h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.20.1=py312h526025d_1
  - torchaudio=2.5.1=py312_cu121
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu121
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - transformers=4.46.3=pyhd8ed1ab_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.44.0=py312h06a4308_0
  - xgboost=2.1.1=py312h06a4308_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py312h5eee18b_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anyio==4.9.0
      - click==8.1.8
      - colorama==0.4.6
      - griffe==1.7.2
      - httpx-sse==0.4.0
      - mcp==1.6.0
      - openai==1.72.0
      - openai-agents==0.0.9
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydantic-settings==2.8.1
      - python-dotenv==1.1.0
      - sse-starlette==2.2.1
      - starlette==0.46.1
      - types-requests==2.32.0.20250328
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - uvicorn==0.34.0
prefix: /home/ruc/anaconda3/envs/optimus
